=== schenkmi/electronic-projects/retro/one-rom/rom-config/schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Config",
    "description": "Top level configuration structure",
    "type": "object",
    "properties": {
        "categories": {
            "description": "Optional categories for this configuration, to aid in grouping,\nsorting, and searching of configurations.",
            "type": [
                "array",
                "null"
            ],
            "items": {
                "type": "string"
            }
        },
        "description": {
            "description": "Mandatory description for this configuration.  This is included in the\ndescription output by the builder, following the name.",
            "type": "string"
        },
        "detail": {
            "description": "Optional detailed description for this configuration.  This is included\nin the description output by the builder, following name and\ndescription.",
            "type": [
                "string",
                "null"
            ]
        },
        "name": {
            "description": "Optional name for this configuration.  Is included in the description\noutput by the builder.",
            "type": [
                "string",
                "null"
            ]
        },
        "notes": {
            "description": "Optional notes for this configuration.  This is included in the\ndescription output by the builder, following the list of images/sets.",
            "type": [
                "string",
                "null"
            ]
        },
        "rom_sets": {
            "description": "Array of ROM set configurations.  Note that even if not using complex\nfeatures like dynamic banking and multi-ROM sets, each ROM image is in\nits own set.\nThe builder description output lists either \"Images\" or \"Sets\"\ndepending on whether there are any multi-set or banked sets in use.",
            "type": "array",
            "items": {
                "$ref": "#/$defs/RomSetConfig"
            }
        },
        "version": {
            "description": "Configuration format version.",
            "const": 1
        }
    },
    "required": [
        "version",
        "description",
        "rom_sets"
    ],
    "$defs": {
        "CsLogic": {
            "description": "Possible Chip Select line logic options",
            "oneOf": [
                {
                    "description": "Chip Select line is active low",
                    "type": "string",
                    "const": "active_low"
                },
                {
                    "description": "Chip Select line is active high",
                    "type": "string",
                    "const": "active_high"
                },
                {
                    "description": "Used for 2332/2316 ROMs, when a CS line isn't used because it's always\ntied active.",
                    "type": "string",
                    "const": "ignore"
                }
            ]
        },
        "Location": {
            "description": "Location within a larger ROM image that the specific image to use resides",
            "type": "object",
            "properties": {
                "length": {
                    "description": "Length of the image within the larger ROM image.  Must match the\nselected ROM type, or SizeHandling will be applied.",
                    "type": "integer",
                    "format": "uint",
                    "minimum": 0
                },
                "start": {
                    "description": "Start of the image within the larger ROM image",
                    "type": "integer",
                    "format": "uint",
                    "minimum": 0
                }
            },
            "required": [
                "start",
                "length"
            ]
        },
        "RomConfig": {
            "description": "ROM configuration structure",
            "type": "object",
            "properties": {
                "cs1": {
                    "description": "Optional Chip Select 1 logic - only valid for ROM Types that have CS1",
                    "anyOf": [
                        {
                            "$ref": "#/$defs/CsLogic"
                        },
                        {
                            "type": "null"
                        }
                    ]
                },
                "cs2": {
                    "description": "Optional Chip Select 2 logic - only valid for ROM Types that have CS2",
                    "anyOf": [
                        {
                            "$ref": "#/$defs/CsLogic"
                        },
                        {
                            "type": "null"
                        }
                    ]
                },
                "cs3": {
                    "description": "Optional Chip Select 3 logic - only valid for ROM Types that have CS3",
                    "anyOf": [
                        {
                            "$ref": "#/$defs/CsLogic"
                        },
                        {
                            "type": "null"
                        }
                    ]
                },
                "description": {
                    "description": "Optional description for this configuration.  This is included in the\ndescription output by the builder.",
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "extract": {
                    "description": "Optional extract path within an archive (zip/tar) if the file pointed\nto is an archive.",
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "file": {
                    "description": "Filename or URL of the ROM image - filename is only valid if using a\ngenerator tool with local file access.  This is passed to the generator\ntool to retrieve the ROM image.",
                    "type": "string"
                },
                "label": {
                    "description": "Optional label for this ROM image.  If specified, this is used in\nmetadata instead of the filename (which itself can be complex if\nextracting a file from an image and providing location information)",
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "license": {
                    "description": "Optional license URL/identifier for the ROM.  This is passed to the\ngenerator tool to retrieve and ask the user to accept before building.",
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "location": {
                    "description": "Optional location within a larger image file.  Used to specify start\noffset and length within the file.  Useful when multiple ROM images\nare concatenated into a single file and one needs to be extracted.",
                    "anyOf": [
                        {
                            "$ref": "#/$defs/Location"
                        },
                        {
                            "type": "null"
                        }
                    ]
                },
                "size_handling": {
                    "description": "Optional size handling configuration for this ROM.  Used to specify\nhandling when the image supplied isn't the correct size for this ROM\ntype.",
                    "$ref": "#/$defs/SizeHandling",
                    "default": "none"
                },
                "type": {
                    "description": "Type of ROM",
                    "$ref": "#/$defs/RomType"
                }
            },
            "required": [
                "file",
                "type"
            ]
        },
        "RomSetConfig": {
            "description": "ROM Set configuration structure",
            "type": "object",
            "properties": {
                "description": {
                    "description": "Optional description for this ROM set.  This is included in the\ndescription output by the builder.",
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "roms": {
                    "description": "Array of ROM configurations in this set.  Contains 1 member for single\nROM sets, and multiple members for multi-ROM and banked ROM sets.",
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/RomConfig"
                    }
                },
                "type": {
                    "description": "Type of ROM set",
                    "$ref": "#/$defs/RomSetType",
                    "default": "single"
                }
            },
            "required": [
                "roms"
            ]
        },
        "RomSetType": {
            "description": "Type of ROM set",
            "oneOf": [
                {
                    "description": "Single ROM - the default",
                    "type": "string",
                    "const": "single"
                },
                {
                    "description": "Set of dynamically banked ROMs. Used to switch between active ROM at\nruntime using jumpers",
                    "type": "string",
                    "const": "banked"
                },
                {
                    "description": "Set of multiple ROMs selected by CS lines.  This allows a single One\nROM to serve up to 3 ROM sockets simultaneously.",
                    "type": "string",
                    "const": "multi"
                }
            ]
        },
        "RomType": {
            "description": "ROM chip type\n\nSupported retro ROM chip types with their pinouts and characteristics.\nIncludes mask ROMs (23xx series) and EPROMs (27xx series).\n\n# Examples\n\n```\nuse onerom_config::rom::RomType;\n\nlet rom = RomType::Rom2364;\nassert_eq!(rom.size_bytes(), 8192);\nassert_eq!(rom.rom_pins(), 24);\nassert_eq!(rom.num_addr_lines(), 13);\n```",
            "oneOf": [
                {
                    "description": "512B EPROM with multiple supply voltages - 512 bytes, 24-pin package",
                    "type": "string",
                    "const": "2704"
                },
                {
                    "description": "1KB EPROM with multiple supply voltages - 1024 bytes, 24-pin package",
                    "type": "string",
                    "const": "2708"
                },
                {
                    "description": "2KB mask ROM with 3 configurable CS lines - 2048 bytes, 24-pin package",
                    "type": "string",
                    "const": "2316"
                },
                {
                    "description": "2KB EPROM with fixed active-low CE/OE - 2048 bytes, 24-pin package",
                    "type": "string",
                    "const": "2716"
                },
                {
                    "description": "4KB mask ROM with 2 configurable CS lines - 4096 bytes, 24-pin package",
                    "type": "string",
                    "const": "2332"
                },
                {
                    "description": "4KB EPROM with fixed active-low CE and shared OE/VPP - 4096 bytes, 24-pin package",
                    "type": "string",
                    "const": "2732"
                },
                {
                    "description": "8KB mask ROM with 1 configurable CS line - 8192 bytes, 24-pin package",
                    "type": "string",
                    "const": "2364"
                },
                {
                    "description": "8KB EPROM with fixed active-low CE/OE - 8192 bytes, 28-pin package",
                    "type": "string",
                    "const": "2764"
                },
                {
                    "description": "16KB mask ROM with 3 configurable CS lines - 16384 bytes, 28-pin package",
                    "type": "string",
                    "const": "23128"
                },
                {
                    "description": "16KB EPROM with fixed active-low CE/OE - 16384 bytes, 28-pin package",
                    "type": "string",
                    "const": "27128"
                },
                {
                    "description": "32KB mask ROM with 2 configurable CS lines - 32768 bytes, 28-pin package",
                    "type": "string",
                    "const": "23256"
                },
                {
                    "description": "32KB EPROM with fixed active-low CE/OE - 32768 bytes, 28-pin package",
                    "type": "string",
                    "const": "27256"
                },
                {
                    "description": "64KB mask ROM with 2 configurable CS lines - 65536 bytes, 28-pin package",
                    "type": "string",
                    "const": "23512"
                },
                {
                    "description": "64KB EPROM with fixed active-low CE/OE - 65536 bytes, 28-pin package",
                    "type": "string",
                    "const": "27512"
                }
            ]
        },
        "SizeHandling": {
            "description": "How to handle ROM images that are too small for the ROM type",
            "oneOf": [
                {
                    "description": "No special handling.  Errors if the image size does not exactly match\nthe ROM size.",
                    "type": "string",
                    "const": "none"
                },
                {
                    "description": "Duplicates the image as many times as needed to fill the ROM.  Errors\nif the image size is not an exact divisor of the ROM size.",
                    "type": "string",
                    "const": "duplicate"
                },
                {
                    "description": "Truncates the image to fit the ROM size.  Errors if the image is an\nexact match size-wise.",
                    "type": "string",
                    "const": "truncate"
                },
                {
                    "description": "Pads the image out with [`PAD_BLANK_BYTE`].",
                    "type": "string",
                    "const": "pad"
                }
            ]
        }
    }
}

=== schenkmi/electronic-projects/retro/one-rom/rom-config/c64.json
{
    "$schema": "https://images.onerom.org/configs/schema.json",
    "version": 1,
    "name": "C64",
    "description": "Standard set of stock C64 ROMs",
    "categories": [
        "computer",
        "firmware",
        "commodore",
        "diag",
        "c64"
    ],
    "rom_sets": [
        {
            "type": "single",
            "roms": [
                {
                    "description": "C64 8KB Kernal ROM, 901227-03",
                    "file": "https://www.zimmers.net/anonftp/pub/cbm/firmware/computers/c64/kernal.901227-03.bin",
                    "type": "2364",
                    "cs1": "active_low"
                }
            ]
        },
        {
            "type": "single",
            "roms": [
                {
                    "description": "C64 8KB Basic ROM, 901226-01",
                    "file": "https://www.zimmers.net/anonftp/pub/cbm/firmware/computers/c64/basic.901226-01.bin",
                    "type": "2364",
                    "cs1": "active_low"
                }
            ]
        },
        {
            "type": "single",
            "roms": [
                {
                    "description": "C64 4KB Character ROM, 901225-01",
                    "file": "https://www.zimmers.net/anonftp/pub/cbm/firmware/computers/c64/characters.901225-01.bin",
                    "type": "2332",
                    "cs1": "active_low",
                    "cs2": "active_high"
                }
            ]
        },
        {
            "type": "single",
            "roms": [
                {
                    "description": "C64 8KB Dead Test Kernal ($E000) ROM, 781220",
                    "file": "https://www.zimmers.net/anonftp/pub/cbm/firmware/misc/c64diag/c64_diag-rev781220-pn314139-03.zip",
                    "extract": "Diag_DeadTest/dead test.BIN",
                    "type": "2364",
                    "cs1": "active_low"
                }
            ]
        }
    ]
}

=== schenkmi/electronic-projects/retro/one-rom/rom-config/4040.json
{
    "$schema": "https://images.onerom.org/configs/schema.json",
    "version": 1,
    "name": "4040",
    "description": "Stock ROMs for DOS2 4040 (and 2040/3040) IEEE disk drives",
    "categories": [
        "drive",
        "firmware",
        "commodore",
        "ieee"
    ],
    "rom_sets": [
        {
            "type": "single",
            "roms": [
                {
                    "description": "$F000 4KB ROM, 901468-16",
                    "file": "http://www.zimmers.net/anonftp/pub/cbm/firmware/drives/old/4040/901468-16.bin",
                    "type": "2332",
                    "cs1": "active_low",
                    "cs2": "active_high"
                }
            ]
        },
        {
            "type": "single",
            "roms": [
                {
                    "description": "$E000 4KB ROM, 901468-15",
                    "file": "http://www.zimmers.net/anonftp/pub/cbm/firmware/drives/old/4040/901468-15.bin",
                    "type": "2332",
                    "cs1": "active_low",
                    "cs2": "active_high"
                }
            ]
        },
        {
            "type": "single",
            "roms": [
                {
                    "description": "$D000 4KB ROM, 901468-14",
                    "file": "http://www.zimmers.net/anonftp/pub/cbm/firmware/drives/old/4040/901468-14.bin",
                    "type": "2332",
                    "cs1": "active_low",
                    "cs2": "active_high"
                }
            ]
        },
        {
            "type": "single",
            "roms": [
                {
                    "description": "$F000 4KB ROM, 901468-13",
                    "file": "http://www.zimmers.net/anonftp/pub/cbm/firmware/drives/old/4040/901468-13.bin",
                    "type": "2332",
                    "cs1": "active_low",
                    "cs2": "active_high"
                }
            ]
        },
        {
            "type": "single",
            "roms": [
                {
                    "description": "$E000 4KB ROM, 901468-12",
                    "file": "http://www.zimmers.net/anonftp/pub/cbm/firmware/drives/old/4040/901468-12.bin",
                    "type": "2332",
                    "cs1": "active_low",
                    "cs2": "active_high"
                }
            ]
        },
        {
            "type": "single",
            "roms": [
                {
                    "description": "$D000 4KB ROM, 901468-11",
                    "file": "http://www.zimmers.net/anonftp/pub/cbm/firmware/drives/old/4040/901468-11.bin",
                    "type": "2332",
                    "cs1": "active_low",
                    "cs2": "active_high"
                }
            ]
        }
    ]
}

=== schenkmi/electronic-projects/retro/one-rom/rom-config/28-c64c.json
{
    "$schema": "https://images.onerom.org/configs/schema.json",
    "version": 1,
    "name": "C64C",
    "description": "Stock 28-pin ROM images for a C64C",
    "categories": [
        "computer",
        "firmware",
        "commodore",
        "c64"
    ],
    "rom_sets": [
        {
            "type": "single",
            "roms": [
                {
                    "description": "16KB BASIC+Kernal ROM, 251913-01",
                    "file": "http://www.zimmers.net/anonftp/pub/cbm/firmware/computers/c64/64c.251913-01.bin",
                    "type": "23128",
                    "cs1": "active_low",
                    "cs2": "active_low",
                    "cs3": "active_high"
                }
            ]
        }
    ]
}

=== schenkmi/electronic-projects/retro/one-rom/rom-config/coco2.json
{
    "$schema": "https://images.onerom.org/configs/schema.json",
    "version": 1,
    "name": "CoCo 2",
    "description": "Stock ROMs for a Tandy Color Computer 2",
    "categories": [
        "computer",
        "firmware",
        "tandy",
        "coco"
    ],
    "rom_sets": [
        {
            "type": "single",
            "roms": [
                {
                    "description": "8KB Color Basic 1.3",
                    "file": "https://archive.org/download/mame-0.221-roms-merged/coco.zip",
                    "extract": "coco2b/bas13.rom",
                    "type": "2364",
                    "cs1": "active_low"
                }
            ]
        },
        {
            "type": "single",
            "roms": [
                {
                    "description": "8KB Extended Color Basic 1.1",
                    "file": "https://archive.org/download/mame-0.221-roms-merged/coco.zip",
                    "extract": "coco2/extbas11.rom",
                    "type": "2364",
                    "cs1": "active_low"
                }
            ]
        },
        {
            "type": "single",
            "roms": [
                {
                    "description": "8KB Color Basic 1.2",
                    "file": "https://archive.org/download/mame-0.221-roms-merged/coco.zip",
                    "extract": "coco2/bas12.rom",
                    "type": "2364",
                    "cs1": "active_low"
                }
            ]
        }
    ]
}

=== schenkmi/electronic-projects/retro/one-rom/rom-config/set-c64.json
{
    "$schema": "https://images.onerom.org/configs/schema.json",
    "version": 1,
    "name": "C64 Complete ROM Sets",
    "description": "Serves a set of stock ROMs for a C64 - all of kernal, basic and character ROMs - when installed in the kernal socket",
    "detail": "The Dead Test Kernal ROM 781220 is installed as set 1.\n\nInstructions:\n1. Install ROM in (kernal) socket\n2. Connect Basic ROM socket CS pin (20) to SDRR pin X1\n3. Connect Character ROM socket CS1 pin (20) to SDRR pin X2\n4. Use SDRR image select jumpers to select required set, 0 = all open\n\nImage details:\n\nSet 0:\na. Kernal ROM 901227-03\nb. Basic ROM 901226-01\nc. Character ROM 901225-01\n\nSet 1:\na. Dead Test Kernal ROM 781220\nb. Character ROM 901225-01\n\nSet 2:\na. Kernal ROM 901227-03, Basic ROM, 901\nb. Basic ROM 901226-01",
    "categories": [
        "computer",
        "firmware",
        "commodore",
        "diag",
        "c64"
    ],
    "rom_sets": [
        {
            "type": "multi",
            "description": "Complete C64 ROM set",
            "roms": [
                {
                    "description": "Kernal ROM 901227-03",
                    "file": "http://www.zimmers.net/anonftp/pub/cbm/firmware/computers/c64/kernal.901227-03.bin",
                    "type": "2364",
                    "cs1": "active_low"
                },
                {
                    "description": "Basic ROM 901226-01",
                    "file": "http://www.zimmers.net/anonftp/pub/cbm/firmware/computers/c64/basic.901226-01.bin",
                    "type": "2364",
                    "cs1": "active_low"
                },
                {
                    "description": "Character ROM 901225-01",
                    "file": "http://www.zimmers.net/anonftp/pub/cbm/firmware/computers/c64/characters.901225-01.bin",
                    "type": "2332",
                    "cs1": "active_low",
                    "cs2": "ignore"
                }
            ]
        },
        {
            "type": "multi",
            "description": "Dead Test with Character ROM",
            "roms": [
                {
                    "description": "Dead Test Kernal ROM 781220",
                    "file": "http://www.zimmers.net/anonftp/pub/cbm/firmware/misc/c64diag/c64_diag-rev781220-pn314139-03.zip",
                    "extract": "Diag_DeadTest/dead test.BIN",
                    "type": "2364",
                    "cs1": "active_low"
                },
                {
                    "description": "Character ROM 901225-01",
                    "file": "http://www.zimmers.net/anonftp/pub/cbm/firmware/computers/c64/characters.901225-01.bin",
                    "type": "2332",
                    "cs1": "active_low",
                    "cs2": "ignore"
                }
            ]
        },
        {
            "type": "multi",
            "description": "Kernal and Basic only",
            "roms": [
                {
                    "description": "Kernal ROM 901227-03",
                    "file": "http://www.zimmers.net/anonftp/pub/cbm/firmware/computers/c64/kernal.901227-03.bin",
                    "type": "2364",
                    "cs1": "active_low"
                },
                {
                    "description": "Basic ROM 901226-01",
                    "file": "http://www.zimmers.net/anonftp/pub/cbm/firmware/computers/c64/basic.901226-01.bin",
                    "type": "2364",
                    "cs1": "active_low"
                }
            ]
        }
    ],
    "notes": "Character ROM CS2 is set to `ignore` as is it tied to 5V within the C64, so always active. Requires HW_REV=f"
}

=== schenkmi/electronic-projects/retro/one-rom/rom-config/c64-inc-destestmax.json
{
    "$schema": "https://images.onerom.org/configs/schema.json",
    "version": 1,
    "name": "C64",
    "description": "Stock ROMs for a C64 including the DesTestMAX diagnostic ROM",
    "categories": [
        "computer",
        "firmware",
        "commodore",
        "diag",
        "c64"
    ],
    "rom_sets": [
        {
            "type": "single",
            "roms": [
                {
                    "description": "8KB Kernal ROM, 901227-03",
                    "file": "http://www.zimmers.net/anonftp/pub/cbm/firmware/computers/c64/kernal.901227-03.bin",
                    "type": "2364",
                    "cs1": "active_low"
                }
            ]
        },
        {
            "type": "single",
            "roms": [
                {
                    "description": "8KB Basic ROM, 901226-01",
                    "file": "http://www.zimmers.net/anonftp/pub/cbm/firmware/computers/c64/basic.901226-01.bin",
                    "type": "2364",
                    "cs1": "active_low"
                }
            ]
        },
        {
            "type": "single",
            "roms": [
                {
                    "description": "4KB Character ROM, 901225-01",
                    "file": "http://www.zimmers.net/anonftp/pub/cbm/firmware/computers/c64/characters.901225-01.bin",
                    "type": "2332",
                    "cs1": "active_low",
                    "cs2": "active_high"
                }
            ]
        },
        {
            "type": "single",
            "roms": [
                {
                    "description": "8KB Dead Test Kernal ($E000) ROM, 781220",
                    "file": "http://www.zimmers.net/anonftp/pub/cbm/firmware/misc/c64diag/c64_diag-rev781220-pn314139-03.zip",
                    "extract": "Diag_DeadTest/dead test.BIN",
                    "type": "2364",
                    "cs1": "active_low"
                }
            ]
        },
        {
            "type": "single",
            "roms": [
                {
                    "description": "8KB DesTestMAX Kernal ($E000) ROM - https://factorofmatt.com/destestmax",
                    "file": "https://img1.wsimg.com/blobby/go/66231677-2ba7-409f-8dee-bbd44bbf8f37/downloads/destest-max-v0.1.zip?ver=1750944987245",
                    "extract": "destest-max.rom",
                    "licence": "https://factorofmatt.com/destestmax%2Fdestestmax-sl",
                    "type": "2364",
                    "cs1": "active_low"
                }
            ]
        }
    ]
}

=== schenkmi/electronic-projects/retro/one-rom/rom-config/ti994a.json
{
    "$schema": "https://images.onerom.org/configs/schema.json",
    "version": 1,
    "name": "TI-99/4A",
    "description": "Stock ROMs for a TI-99 4/a",
    "categories": [
        "computer",
        "firmware",
        "ti",
        "ti99"
    ],
    "rom_sets": [
        {
            "type": "single",
            "roms": [
                {
                    "description": "4KB HB System ROM",
                    "file": "https://archive.org/download/mame-0.221-roms-merged/ti99_4a.zip",
                    "extract": "994a_rom_hb.u610",
                    "type": "2332",
                    "cs1": "active_low",
                    "cs2": "active_low"
                }
            ]
        },
        {
            "type": "single",
            "roms": [
                {
                    "description": "4KB LB System ROM",
                    "file": "https://archive.org/download/mame-0.221-roms-merged/ti99_4a.zip",
                    "extract": "994a_rom_lb.u611",
                    "type": "2332",
                    "cs1": "active_low",
                    "cs2": "active_low"
                }
            ]
        }
    ]
}
