=== schenkmi/electronic-projects/retro/one-rom/rom-config/schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Config",
    "description": "Top level configuration structure",
    "type": "object",
    "properties": {
        "categories": {
            "description": "Optional categories for this configuration, to aid in grouping,\nsorting, and searching of configurations.",
            "type": [
                "array",
                "null"
            ],
            "items": {
                "type": "string"
            }
        },
        "description": {
            "description": "Mandatory description for this configuration.  This is included in the\ndescription output by the builder, following the name.",
            "type": "string"
        },
        "detail": {
            "description": "Optional detailed description for this configuration.  This is included\nin the description output by the builder, following name and\ndescription.",
            "type": [
                "string",
                "null"
            ]
        },
        "name": {
            "description": "Optional name for this configuration.  Is included in the description\noutput by the builder.",
            "type": [
                "string",
                "null"
            ]
        },
        "notes": {
            "description": "Optional notes for this configuration.  This is included in the\ndescription output by the builder, following the list of images/sets.",
            "type": [
                "string",
                "null"
            ]
        },
        "rom_sets": {
            "description": "Array of ROM set configurations.  Note that even if not using complex\nfeatures like dynamic banking and multi-ROM sets, each ROM image is in\nits own set.\nThe builder description output lists either \"Images\" or \"Sets\"\ndepending on whether there are any multi-set or banked sets in use.",
            "type": "array",
            "items": {
                "$ref": "#/$defs/RomSetConfig"
            }
        },
        "version": {
            "description": "Configuration format version.",
            "const": 1
        }
    },
    "required": [
        "version",
        "description",
        "rom_sets"
    ],
    "$defs": {
        "CsLogic": {
            "description": "Possible Chip Select line logic options",
            "oneOf": [
                {
                    "description": "Chip Select line is active low",
                    "type": "string",
                    "const": "active_low"
                },
                {
                    "description": "Chip Select line is active high",
                    "type": "string",
                    "const": "active_high"
                },
                {
                    "description": "Used for 2332/2316 ROMs, when a CS line isn't used because it's always\ntied active.",
                    "type": "string",
                    "const": "ignore"
                }
            ]
        },
        "Location": {
            "description": "Location within a larger ROM image that the specific image to use resides",
            "type": "object",
            "properties": {
                "length": {
                    "description": "Length of the image within the larger ROM image.  Must match the\nselected ROM type, or SizeHandling will be applied.",
                    "type": "integer",
                    "format": "uint",
                    "minimum": 0
                },
                "start": {
                    "description": "Start of the image within the larger ROM image",
                    "type": "integer",
                    "format": "uint",
                    "minimum": 0
                }
            },
            "required": [
                "start",
                "length"
            ]
        },
        "RomConfig": {
            "description": "ROM configuration structure",
            "type": "object",
            "properties": {
                "cs1": {
                    "description": "Optional Chip Select 1 logic - only valid for ROM Types that have CS1",
                    "anyOf": [
                        {
                            "$ref": "#/$defs/CsLogic"
                        },
                        {
                            "type": "null"
                        }
                    ]
                },
                "cs2": {
                    "description": "Optional Chip Select 2 logic - only valid for ROM Types that have CS2",
                    "anyOf": [
                        {
                            "$ref": "#/$defs/CsLogic"
                        },
                        {
                            "type": "null"
                        }
                    ]
                },
                "cs3": {
                    "description": "Optional Chip Select 3 logic - only valid for ROM Types that have CS3",
                    "anyOf": [
                        {
                            "$ref": "#/$defs/CsLogic"
                        },
                        {
                            "type": "null"
                        }
                    ]
                },
                "description": {
                    "description": "Optional description for this configuration.  This is included in the\ndescription output by the builder.",
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "extract": {
                    "description": "Optional extract path within an archive (zip/tar) if the file pointed\nto is an archive.",
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "file": {
                    "description": "Filename or URL of the ROM image - filename is only valid if using a\ngenerator tool with local file access.  This is passed to the generator\ntool to retrieve the ROM image.",
                    "type": "string"
                },
                "label": {
                    "description": "Optional label for this ROM image.  If specified, this is used in\nmetadata instead of the filename (which itself can be complex if\nextracting a file from an image and providing location information)",
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "license": {
                    "description": "Optional license URL/identifier for the ROM.  This is passed to the\ngenerator tool to retrieve and ask the user to accept before building.",
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "location": {
                    "description": "Optional location within a larger image file.  Used to specify start\noffset and length within the file.  Useful when multiple ROM images\nare concatenated into a single file and one needs to be extracted.",
                    "anyOf": [
                        {
                            "$ref": "#/$defs/Location"
                        },
                        {
                            "type": "null"
                        }
                    ]
                },
                "size_handling": {
                    "description": "Optional size handling configuration for this ROM.  Used to specify\nhandling when the image supplied isn't the correct size for this ROM\ntype.",
                    "$ref": "#/$defs/SizeHandling",
                    "default": "none"
                },
                "type": {
                    "description": "Type of ROM",
                    "$ref": "#/$defs/RomType"
                }
            },
            "required": [
                "file",
                "type"
            ]
        },
        "RomSetConfig": {
            "description": "ROM Set configuration structure",
            "type": "object",
            "properties": {
                "description": {
                    "description": "Optional description for this ROM set.  This is included in the\ndescription output by the builder.",
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "roms": {
                    "description": "Array of ROM configurations in this set.  Contains 1 member for single\nROM sets, and multiple members for multi-ROM and banked ROM sets.",
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/RomConfig"
                    }
                },
                "type": {
                    "description": "Type of ROM set",
                    "$ref": "#/$defs/RomSetType",
                    "default": "single"
                }
            },
            "required": [
                "roms"
            ]
        },
        "RomSetType": {
            "description": "Type of ROM set",
            "oneOf": [
                {
                    "description": "Single ROM - the default",
                    "type": "string",
                    "const": "single"
                },
                {
                    "description": "Set of dynamically banked ROMs. Used to switch between active ROM at\nruntime using jumpers",
                    "type": "string",
                    "const": "banked"
                },
                {
                    "description": "Set of multiple ROMs selected by CS lines.  This allows a single One\nROM to serve up to 3 ROM sockets simultaneously.",
                    "type": "string",
                    "const": "multi"
                }
            ]
        },
        "RomType": {
            "description": "ROM chip type\n\nSupported retro ROM chip types with their pinouts and characteristics.\nIncludes mask ROMs (23xx series) and EPROMs (27xx series).\n\n# Examples\n\n```\nuse onerom_config::rom::RomType;\n\nlet rom = RomType::Rom2364;\nassert_eq!(rom.size_bytes(), 8192);\nassert_eq!(rom.rom_pins(), 24);\nassert_eq!(rom.num_addr_lines(), 13);\n```",
            "oneOf": [
                {
                    "description": "512B EPROM with multiple supply voltages - 512 bytes, 24-pin package",
                    "type": "string",
                    "const": "2704"
                },
                {
                    "description": "1KB EPROM with multiple supply voltages - 1024 bytes, 24-pin package",
                    "type": "string",
                    "const": "2708"
                },
                {
                    "description": "2KB mask ROM with 3 configurable CS lines - 2048 bytes, 24-pin package",
                    "type": "string",
                    "const": "2316"
                },
                {
                    "description": "2KB EPROM with fixed active-low CE/OE - 2048 bytes, 24-pin package",
                    "type": "string",
                    "const": "2716"
                },
                {
                    "description": "4KB mask ROM with 2 configurable CS lines - 4096 bytes, 24-pin package",
                    "type": "string",
                    "const": "2332"
                },
                {
                    "description": "4KB EPROM with fixed active-low CE and shared OE/VPP - 4096 bytes, 24-pin package",
                    "type": "string",
                    "const": "2732"
                },
                {
                    "description": "8KB mask ROM with 1 configurable CS line - 8192 bytes, 24-pin package",
                    "type": "string",
                    "const": "2364"
                },
                {
                    "description": "8KB EPROM with fixed active-low CE/OE - 8192 bytes, 28-pin package",
                    "type": "string",
                    "const": "2764"
                },
                {
                    "description": "16KB mask ROM with 3 configurable CS lines - 16384 bytes, 28-pin package",
                    "type": "string",
                    "const": "23128"
                },
                {
                    "description": "16KB EPROM with fixed active-low CE/OE - 16384 bytes, 28-pin package",
                    "type": "string",
                    "const": "27128"
                },
                {
                    "description": "32KB mask ROM with 2 configurable CS lines - 32768 bytes, 28-pin package",
                    "type": "string",
                    "const": "23256"
                },
                {
                    "description": "32KB EPROM with fixed active-low CE/OE - 32768 bytes, 28-pin package",
                    "type": "string",
                    "const": "27256"
                },
                {
                    "description": "64KB mask ROM with 2 configurable CS lines - 65536 bytes, 28-pin package",
                    "type": "string",
                    "const": "23512"
                },
                {
                    "description": "64KB EPROM with fixed active-low CE/OE - 65536 bytes, 28-pin package",
                    "type": "string",
                    "const": "27512"
                }
            ]
        },
        "SizeHandling": {
            "description": "How to handle ROM images that are too small for the ROM type",
            "oneOf": [
                {
                    "description": "No special handling.  Errors if the image size does not exactly match\nthe ROM size.",
                    "type": "string",
                    "const": "none"
                },
                {
                    "description": "Duplicates the image as many times as needed to fill the ROM.  Errors\nif the image size is not an exact divisor of the ROM size.",
                    "type": "string",
                    "const": "duplicate"
                },
                {
                    "description": "Truncates the image to fit the ROM size.  Errors if the image is an\nexact match size-wise.",
                    "type": "string",
                    "const": "truncate"
                },
                {
                    "description": "Pads the image out with [`PAD_BLANK_BYTE`].",
                    "type": "string",
                    "const": "pad"
                }
            ]
        }
    }
}

=== schenkmi/electronic-projects/retro/one-rom/rom-config/test-0.json
{
    "$schema": "https://images.onerom.org/configs/schema.json",
    "version": 1,
    "description": "Test ROM images for One ROM firmware and build process",
    "detail": "Contains various ROM images to enable testing the One ROM firmware and build process. Each ROM is a separate single ROM set for independent testing.",
    "rom_sets": [
        {
            "type": "single",
            "description": "Set 0",
            "roms": [
                {
                    "file": "images/test/zero8192.rom",
                    "description": "8KB ROM filled with 0x00",
                    "type": "2364",
                    "cs1": "active_low"
                }
            ]
        },
        {
            "type": "single",
            "description": "Set 1",
            "roms": [
                {
                    "file": "images/test/0_63_8192.rom",
                    "description": "8KB ROM filled with repeating 0x00-0x3F",
                    "type": "2364",
                    "cs1": "active_low"
                }
            ]
        },
        {
            "type": "single",
            "description": "Set 2",
            "roms": [
                {
                    "file": "images/test/0_63_4096.rom",
                    "description": "4KB ROM filled with repeating 0x00-0x3F, CS2 active high",
                    "type": "2332",
                    "cs1": "active_low",
                    "cs2": "active_high"
                }
            ]
        },
        {
            "type": "single",
            "description": "Set 3",
            "roms": [
                {
                    "file": "images/test/0_63_4096.rom",
                    "description": "4KB ROM filled with repeating 0x00-0x3F, CS2 active low",
                    "type": "2332",
                    "cs1": "active_low",
                    "cs2": "active_low"
                }
            ]
        },
        {
            "type": "single",
            "description": "Set 4",
            "roms": [
                {
                    "file": "images/test/0_63_2048.rom",
                    "description": "2KB ROM filled with repeating 0x00-0x3F, CS2/CS3 active high",
                    "type": "2316",
                    "cs1": "active_low",
                    "cs2": "active_high",
                    "cs3": "active_high"
                }
            ]
        },
        {
            "type": "single",
            "description": "Set 5",
            "roms": [
                {
                    "file": "https://github.com/piersfinlayson/pet-ieee-loader/releases/download/v0.1.1/test.bin",
                    "description": "4KB ROM containing a simple PET test program, can be located at any address, CS2 active high, SYS <START ADDRESS> to run",
                    "type": "2332",
                    "cs1": "active_low",
                    "cs2": "active_high",
                    "size_handling": "pad"
                }
            ]
        }
    ]
}

=== schenkmi/electronic-projects/retro/one-rom/rom-config/set-1541.json
{
    "$schema": "https://images.onerom.org/configs/schema.json",
    "version": 1,
    "name": "1541 Multi-ROM Sets",
    "description": "Stock ROMs sets for 1540/1541 drives which use 8KB (2364) ROMs",
    "categories": [
        "drive",
        "firmware",
        "commodore",
        "iec"
    ],
    "rom_sets": [
        {
            "type": "multi",
            "description": "1541 ROM set with 901229-06AA",
            "roms": [
                {
                    "description": "1541/1540 $C000 8KB ROM, 325302-01",
                    "file": "http://www.zimmers.net/anonftp/pub/cbm/firmware/drives/new/1541/1541-c000.325302-01.bin",
                    "type": "2364",
                    "cs1": "active_low"
                },
                {
                    "description": "1541 $E000 8KB ROM, 901229-06AA",
                    "file": "http://www.zimmers.net/anonftp/pub/cbm/firmware/drives/new/1541/1541-e000.901229-06AA.bin",
                    "type": "2364",
                    "cs1": "active_low"
                }
            ]
        },
        {
            "type": "multi",
            "description": "1541 ROM set with 901229-05",
            "roms": [
                {
                    "description": "1541/1540 $C000 8KB ROM, 325302-01",
                    "file": "http://www.zimmers.net/anonftp/pub/cbm/firmware/drives/new/1541/1541-c000.325302-01.bin",
                    "type": "2364",
                    "cs1": "active_low"
                },
                {
                    "description": "1541 $E000 8KB ROM, 901229-05",
                    "file": "http://www.zimmers.net/anonftp/pub/cbm/firmware/drives/new/1541/1541-e000.901229-05.bin",
                    "type": "2364",
                    "cs1": "active_low"
                }
            ]
        },
        {
            "type": "multi",
            "description": "1540 ROM set with 325303-01",
            "roms": [
                {
                    "description": "1541/1540 $C000 8KB ROM, 325302-01",
                    "file": "http://www.zimmers.net/anonftp/pub/cbm/firmware/drives/new/1541/1541-c000.325302-01.bin",
                    "type": "2364",
                    "cs1": "active_low"
                },
                {
                    "description": "1540 $E000 8KB ROM, 325303-01",
                    "file": "http://www.zimmers.net/anonftp/pub/cbm/firmware/drives/new/1541/1540-e000.325303-01.bin",
                    "type": "2364",
                    "cs1": "active_low"
                }
            ]
        }
    ],
    "notes": "The _lower_ ROM ($C000) is the first image in the set. This means you must install SDRR in the $C000 ROM slot (UB3), and connect X1 to pin 20 of the $E000 ROM slot (UB4)."
}

=== schenkmi/electronic-projects/retro/one-rom/rom-config/set-vic20-pal.json
{
    "$schema": "https://images.onerom.org/configs/schema.json",
    "version": 1,
    "name": "VIC-20 PAL Kernal and Basic",
    "description": "Serves a pair of stock ROMs for a PAL VIC20 - both kernal and basic ROMs",
    "detail": "A single One ROM cannot serve the character ROM for the VIC20 at the same time as the KERNAL and BASIC ROMs, as it has a different data bus to the kernal and basic ROMs.\n\nThe VIC20 dead test kernal ROM is installed as set 1.\n\nInstructions:\n1. Install ROM in (kernal) socket\n2. Connect Basic ROM socket CS pin (20) to SDRR pin X1\n3. Use One ROM image select jumpers to select required set, 0 = all open\n\nImage details:\n\nSet 0:\na. Kernal ROM 901487-07\nb. Basic ROM 901486-01\n\nSet 1:\na. Dead Test Kernal ROM, V1.1.01",
    "categories": [
        "computer",
        "firmware",
        "commodore",
        "diag",
        "vic20"
    ],
    "rom_sets": [
        {
            "type": "multi",
            "description": "Kernal and Basic ROMs",
            "roms": [
                {
                    "description": "Kernal ROM 901486-07",
                    "file": "http://www.zimmers.net/anonftp/pub/cbm/firmware/computers/vic20/kernal.901486-07.bin",
                    "type": "2364",
                    "cs1": "active_low"
                },
                {
                    "description": "Basic ROM 901486-01",
                    "file": "http://www.zimmers.net/anonftp/pub/cbm/firmware/computers/vic20/basic.901486-01.bin",
                    "type": "2364",
                    "cs1": "active_low"
                }
            ]
        },
        {
            "type": "single",
            "description": "Dead Test Kernal",
            "roms": [
                {
                    "description": "Dead Test Kernal ROM, V1.1.01",
                    "file": "https://github.com/piersfinlayson/Vic20-dead-test/releases/download/v1.1.01/dead-test.pal.e0",
                    "type": "2364",
                    "cs1": "active_low"
                }
            ]
        }
    ],
    "notes": "Requires HW_REV=f or later"
}

=== schenkmi/electronic-projects/retro/one-rom/rom-config/vic20-ntsc.json
{
    "$schema": "https://images.onerom.org/configs/schema.json",
    "version": 1,
    "name": "VIC-20 NTSC",
    "description": "Stock ROMs for an NTSC VIC-20",
    "categories": [
        "computer",
        "firmware",
        "commodore",
        "diag",
        "vic20"
    ],
    "rom_sets": [
        {
            "type": "single",
            "roms": [
                {
                    "description": "8KB Kernal ROM, 901486-06",
                    "file": "http://www.zimmers.net/anonftp/pub/cbm/firmware/computers/vic20/kernal.901486-06.bin",
                    "type": "2364",
                    "cs1": "active_low"
                }
            ]
        },
        {
            "type": "single",
            "roms": [
                {
                    "description": "8KB Basic ROM, 901486-01",
                    "file": "http://www.zimmers.net/anonftp/pub/cbm/firmware/computers/vic20/basic.901486-01.bin",
                    "type": "2364",
                    "cs1": "active_low"
                }
            ]
        },
        {
            "type": "single",
            "roms": [
                {
                    "description": "4KB Character ROM, 901460-03",
                    "file": "http://www.zimmers.net/anonftp/pub/cbm/firmware/computers/vic20/characters.901460-03.bin",
                    "type": "2332",
                    "cs1": "active_low",
                    "cs2": "active_low"
                }
            ]
        },
        {
            "type": "single",
            "roms": [
                {
                    "description": "8KB Dead Test Kernal ROM (NTSC), V1.1.01",
                    "file": "https://github.com/piersfinlayson/Vic20-dead-test/releases/download/v1.1.01/dead-test.ntsc.e0",
                    "type": "2364",
                    "cs1": "active_low"
                }
            ]
        }
    ]
}

=== schenkmi/electronic-projects/retro/one-rom/rom-config/28-1541ii.json
{
    "$schema": "https://images.onerom.org/configs/schema.json",
    "version": 1,
    "name": "1541-II",
    "description": "Stock 28-pin ROM images for a 1541-II",
    "categories": [
        "drive",
        "firmware",
        "commodore",
        "iec"
    ],
    "rom_sets": [
        {
            "type": "single",
            "roms": [
                {
                    "description": "16KB firmware, 251968-03",
                    "file": "http://www.zimmers.net/anonftp/pub/cbm/firmware/drives/new/1541/1541-II.251968-03.bin",
                    "type": "27128"
                }
            ]
        }
    ],
    "notes": "To do: Add other ROMs"
}

=== schenkmi/electronic-projects/retro/one-rom/rom-config/bank-c64-char.json
{
    "$schema": "https://images.onerom.org/configs/schema.json",
    "version": 1,
    "name": "C64 Character Sets",
    "description": "Dynamically bank switchable C64 character sets",
    "categories": [
        "computer",
        "firmware",
        "commodore",
        "character",
        "c64"
    ],
    "rom_sets": [
        {
            "type": "banked",
            "description": "European character sets",
            "roms": [
                {
                    "description": "4KB Character ROM, English, 901225-01",
                    "file": "http://www.zimmers.net/anonftp/pub/cbm/firmware/computers/c64/characters.901225-01.bin",
                    "type": "2332",
                    "cs1": "active_low",
                    "cs2": "active_high"
                },
                {
                    "description": "4KB Character ROM, Swedish, 325018-02",
                    "file": "http://www.zimmers.net/anonftp/pub/cbm/firmware/computers/c64/characters.325018-02.bin",
                    "type": "2332",
                    "cs1": "active_low",
                    "cs2": "active_high"
                },
                {
                    "description": "4KB Character ROM, Spanish, 325056-03",
                    "file": "http://www.zimmers.net/anonftp/pub/cbm/firmware/computers/c64/characters.325056-03.bin",
                    "type": "2332",
                    "cs1": "active_low",
                    "cs2": "active_high"
                },
                {
                    "description": "4KB Character ROM, Danish, 901225-01-DK",
                    "file": "http://www.zimmers.net/anonftp/pub/cbm/firmware/computers/c64/characters.901225-01-DK.bin",
                    "type": "2332",
                    "cs1": "active_low",
                    "cs2": "active_high"
                }
            ]
        },
        {
            "type": "banked",
            "description": "International character sets",
            "roms": [
                {
                    "description": "4KB Character ROM, English, 901225-01",
                    "file": "http://www.zimmers.net/anonftp/pub/cbm/firmware/computers/c64/characters.901225-01.bin",
                    "type": "2332",
                    "cs1": "active_low",
                    "cs2": "active_high"
                },
                {
                    "description": "4KB Character ROM, Turkish",
                    "file": "http://www.zimmers.net/anonftp/pub/cbm/firmware/computers/c64/characters.turkish.bin",
                    "type": "2332",
                    "cs1": "active_low",
                    "cs2": "active_high"
                },
                {
                    "description": "4KB Character ROM, Croatian",
                    "file": "http://www.zimmers.net/anonftp/pub/cbm/firmware/computers/c64/croatian.zip",
                    "extract": "c64_cro/chargen",
                    "type": "2332",
                    "cs1": "active_low",
                    "cs2": "active_high"
                },
                {
                    "description": "4KB Character ROM, Japanese, 906143-02",
                    "file": "http://www.zimmers.net/anonftp/pub/cbm/firmware/computers/c64/characters.906143-02.bin",
                    "type": "2332",
                    "cs1": "active_low",
                    "cs2": "active_high"
                }
            ]
        }
    ]
}
